[2017-11-02 17:14:19,586: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 17:14:19,910: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 17:14:19,934: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 17:14:20,947: INFO/MainProcess] mingle: all alone
[2017-11-02 17:14:20,966: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 17:14:20,969: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:20,973: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:20,976: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:20,978: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:20,980: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:20,984: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:20,987: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:20,988: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:20,990: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:20,993: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:20,994: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:20,995: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:20,997: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:20,998: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:20,999: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,001: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,002: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:21,004: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,019: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:21,023: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:21,025: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:21,028: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:21,035: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,041: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,046: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,049: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,055: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:21,058: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:21,060: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:21,062: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:21,064: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,066: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,071: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:21,074: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:21,076: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,080: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,083: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,085: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,093: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:21,096: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,098: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,101: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:21,104: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,107: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,115: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,117: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,124: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:14:21,126: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:21,132: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:14:21,134: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:21,137: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,138: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,142: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,145: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,154: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:14:21,156: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:21,157: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:14:21,159: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:21,165: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,169: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,171: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,175: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:14:21,177: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:21,180: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:14:21,182: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,186: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,191: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,193: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,195: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,202: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,204: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:14:21,212: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,215: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,220: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,226: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,234: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,237: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,243: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,249: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,255: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,260: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,266: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,269: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,277: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,282: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,289: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,291: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:14:21,294: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,495: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:15:26,503: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:15:26,505: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:15:26,511: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:15:26,517: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:15:26,521: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,524: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:15:26,531: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:15:26,534: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,536: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,543: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,546: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:15:26,550: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,557: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:15:26,559: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:15:26,563: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,567: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,572: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:15:26,574: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:15:26,578: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:15:26,579: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:15:26,581: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,605: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,611: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,643: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,645: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,656: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:15:26,665: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:20:29,101: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 17:20:29,364: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 17:20:29,389: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 17:20:30,402: INFO/MainProcess] mingle: all alone
[2017-11-02 17:20:30,417: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 17:29:11,851: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:29:11,859: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:29:11,865: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:29:11,870: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:29:11,873: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:29:11,881: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:29:11,883: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:29:11,892: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,899: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,902: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,909: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,916: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,919: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:11,924: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,646: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:29:14,649: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:29:14,653: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:29:14,657: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:29:14,658: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:29:14,664: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:29:14,668: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,672: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:29:14,674: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,679: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,682: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,691: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,693: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:29:14,696: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,103: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:31:15,115: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,120: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:31:15,123: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:31:15,125: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:31:15,127: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:31:15,134: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:31:15,137: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:31:15,143: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,152: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,155: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,159: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,166: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:31:15,172: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,501: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:33:22,508: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:33:22,511: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:33:22,514: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:33:22,518: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:33:22,522: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:33:22,525: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:33:22,531: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,550: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,555: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,560: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,569: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,582: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:22,589: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,229: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:33:45,233: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:33:45,237: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:33:45,243: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:33:45,245: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:33:45,250: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,256: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,258: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:33:45,260: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:33:45,262: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,272: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,275: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,280: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:33:45,282: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,621: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:34:07,626: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:34:07,631: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:34:07,638: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,640: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:34:07,642: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:34:07,648: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:34:07,652: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,658: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,661: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:34:07,666: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,672: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,675: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:07,680: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,518: INFO/MainProcess] Received task: app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558]
[2017-11-02 17:34:09,523: INFO/MainProcess] Received task: app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268]
[2017-11-02 17:34:09,526: INFO/MainProcess] Received task: app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80]
[2017-11-02 17:34:09,530: INFO/MainProcess] Received task: app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd]
[2017-11-02 17:34:09,533: INFO/MainProcess] Received task: app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954]
[2017-11-02 17:34:09,537: INFO/MainProcess] Received task: app.script_runner[dc82762e-881d-41e7-b111-48533f58d194]
[2017-11-02 17:34:09,540: INFO/MainProcess] Received task: app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e]
[2017-11-02 17:34:09,542: ERROR/MainProcess] Task app.script_runner[5fb8496a-d4a9-4be5-9746-8e3feb1c8558] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,561: ERROR/MainProcess] Task app.script_runner[f13164d7-2c79-4823-bc7c-afdfb3414268] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,566: ERROR/MainProcess] Task app.script_runner[c59897d9-3c53-406f-99fe-04b8bd307f80] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,571: ERROR/MainProcess] Task app.script_runner[9d623c6b-7500-42db-ba82-44a72507bedd] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,574: ERROR/MainProcess] Task app.script_runner[da78fca7-4bdd-4989-8302-cb646ab2f954] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,579: ERROR/MainProcess] Task app.script_runner[dc82762e-881d-41e7-b111-48533f58d194] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:34:09,581: ERROR/MainProcess] Task app.script_runner[7c11fdf3-5887-48ae-ae09-9a0752235e5e] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:36:42,170: INFO/MainProcess] Received task: app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9]
[2017-11-02 17:36:42,184: INFO/Worker-4] app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9]: ###  Matthew in script_runner celery task  ###
[2017-11-02 17:37:53,650: INFO/MainProcess] Received task: app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9]
[2017-11-02 17:37:53,664: ERROR/MainProcess] Task app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 17:45:23,684: INFO/Worker-4] app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9]: ###  !!!  Matthew in script_runner celery has now completed  !!!  ###
[2017-11-02 17:45:23,685: INFO/Worker-4] app.script_runner[9bdbac19-1e93-4c0a-8c67-d9e244b6f2d9]: ###  Matthew in script_runner removing jobfile jobfile-d21af7f0-cef5-49d2-847e-1138f1b0976a.py  ###
[2017-11-02 17:45:23,762: ERROR/Worker-4] Pool process <Worker(Worker-4, started daemon)> error: BrokenPipeError(32, 'Broken pipe')
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/pool.py", line 371, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 220, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 429, in _send_bytes
    self._send(struct.pack("!i", n))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 392, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/pool.py", line 295, in run
    sys.exit(self.workloop(pid=pid))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/pool.py", line 379, in workloop
    put((READY, (job, i, (False, einfo), inqW_fd)))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 220, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 429, in _send_bytes
    self._send(struct.pack("!i", n))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/billiard/py3/connection.py", line 392, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[2017-11-02 17:45:48,282: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 17:45:48,568: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 17:45:48,592: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 17:45:49,606: INFO/MainProcess] mingle: all alone
[2017-11-02 17:45:49,625: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 17:46:12,176: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 17:46:12,439: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 17:46:12,464: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 17:46:13,476: INFO/MainProcess] mingle: all alone
[2017-11-02 17:46:13,492: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:04:46,334: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:04:46,506: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:04:46,521: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:04:47,531: INFO/MainProcess] mingle: all alone
[2017-11-02 18:04:47,548: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:05:25,182: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:05:25,353: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:05:25,369: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:05:26,379: INFO/MainProcess] mingle: all alone
[2017-11-02 18:05:26,407: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:17:05,733: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:17:06,239: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:17:06,284: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:17:07,301: INFO/MainProcess] mingle: all alone
[2017-11-02 18:17:07,325: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:17:38,855: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:17:49,848: INFO/MainProcess] Received task: app.script_runner[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:17:49,864: ERROR/MainProcess] Task app.script_runner[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: script_runner() missing 8 required positional arguments: 'rtr_hostname', 'rtr_mgmt_ip', 'rtr_username', 'rtr_password', 'platform', 'image_repo', 'tftp_dir', and 'tftp_server_ip'
[2017-11-02 18:17:58,884: INFO/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] succeeded in 20.02726404182613s: None
[2017-11-02 18:19:31,640: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:19:31,926: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:19:31,951: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:19:32,981: INFO/MainProcess] mingle: all alone
[2017-11-02 18:19:32,996: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:19:48,937: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:19:52,623: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:19:52,633: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:19:52,644: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:19:52,656: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:20:08,970: INFO/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] succeeded in 20.031295999884605s: None
[2017-11-02 18:22:20,935: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:22:21,222: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:22:21,254: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:22:22,266: INFO/MainProcess] mingle: all alone
[2017-11-02 18:22:22,293: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:22:25,472: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:22:30,189: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:22:30,200: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:22:30,206: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:22:30,228: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:30,256: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:30,264: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:33,902: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:22:33,904: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:22:33,909: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:22:33,920: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:33,924: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:36,677: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:22:36,683: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:22:36,687: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:22:36,692: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:36,700: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:45,500: INFO/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] succeeded in 20.02671194449067s: None
[2017-11-02 18:22:45,506: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:22:45,510: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:39:02,611: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:39:02,765: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:39:02,780: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:39:03,789: INFO/MainProcess] mingle: all alone
[2017-11-02 18:39:03,815: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:39:03,819: INFO/MainProcess] Received task: app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5]
[2017-11-02 18:39:05,815: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:39:05,838: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:39:23,135: INFO/MainProcess] Received task: app.math[9b6a2659-8015-4dd1-95ca-1085061435bc]
[2017-11-02 18:39:28,206: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:39:28,223: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:39:28,230: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:39:28,235: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:39:28,236: INFO/MainProcess] Received task: app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5]
[2017-11-02 18:39:28,241: INFO/MainProcess] Received task: app.math[9b6a2659-8015-4dd1-95ca-1085061435bc]
[2017-11-02 18:39:28,248: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:39:31,693: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:39:31,698: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:39:31,702: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:39:31,704: INFO/MainProcess] Received task: app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5]
[2017-11-02 18:39:31,707: INFO/MainProcess] Received task: app.math[9b6a2659-8015-4dd1-95ca-1085061435bc]
[2017-11-02 18:39:37,591: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:39:37,597: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:39:37,601: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:39:37,602: INFO/MainProcess] Received task: app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5]
[2017-11-02 18:39:37,605: INFO/MainProcess] Received task: app.math[9b6a2659-8015-4dd1-95ca-1085061435bc]
[2017-11-02 18:39:41,030: INFO/MainProcess] Received task: app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1]
[2017-11-02 18:39:41,033: INFO/MainProcess] Received task: app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904]
[2017-11-02 18:39:41,037: INFO/MainProcess] Received task: app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc]
[2017-11-02 18:41:03,936: INFO/MainProcess] Task app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5] succeeded in 120.11164371110499s: None
[2017-11-02 18:41:03,938: INFO/MainProcess] Received task: app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5]
[2017-11-02 18:41:03,940: INFO/MainProcess] Received task: app.math[9b6a2659-8015-4dd1-95ca-1085061435bc]
[2017-11-02 18:41:03,951: ERROR/MainProcess] Task app.math[9b6a2659-8015-4dd1-95ca-1085061435bc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:03,954: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:03,967: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:03,969: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:03,983: ERROR/MainProcess] Task app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:03,993: ERROR/MainProcess] Task app.math[9b6a2659-8015-4dd1-95ca-1085061435bc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:04,003: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,244: INFO/MainProcess] Task app.math[9b6a2659-8015-4dd1-95ca-1085061435bc] succeeded in 120.10739553533494s: None
[2017-11-02 18:41:23,253: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,260: ERROR/MainProcess] Task app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,273: ERROR/MainProcess] Task app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,277: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,282: ERROR/MainProcess] Task app.math[9b6a2659-8015-4dd1-95ca-1085061435bc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,294: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,299: ERROR/MainProcess] Task app.math[68ae16d2-98ab-4397-98e3-fd4c2e5a5904] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,302: ERROR/MainProcess] Task app.math[1a777d9a-3c03-443c-b5bd-b002d61e5ecc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,311: ERROR/MainProcess] Task app.math[3cb1b062-67e2-4881-98d4-615c0fca27c1] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,313: ERROR/MainProcess] Task app.math[964a0c88-f5d7-460e-98ea-2182bdc266c5] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:41:23,324: ERROR/MainProcess] Task app.math[9b6a2659-8015-4dd1-95ca-1085061435bc] raised unexpected: TypeError("math() missing 2 required positional arguments: 'num1' and 'num2'",)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/ws/mastarke-sjc/my_local_git/image_picker_site/Flask_celery.py", line 12, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: math() missing 2 required positional arguments: 'num1' and 'num2'
[2017-11-02 18:51:57,571: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 18:51:57,742: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 18:51:57,756: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 18:51:58,767: INFO/MainProcess] mingle: all alone
[2017-11-02 18:51:58,791: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 18:52:08,781: INFO/MainProcess] Received task: app.math[ad5db3b1-ab8f-4927-9ccc-7b4429f05c2a]
[2017-11-02 18:54:08,888: INFO/MainProcess] Task app.math[ad5db3b1-ab8f-4927-9ccc-7b4429f05c2a] succeeded in 120.10574072413146s: None
[2017-11-02 18:56:06,940: INFO/MainProcess] Received task: app.math[3a3703f6-d143-44c9-a7f1-230bee00e051]
[2017-11-02 18:58:07,055: INFO/MainProcess] Task app.math[3a3703f6-d143-44c9-a7f1-230bee00e051] succeeded in 120.11376655846834s: None
[2017-11-02 18:59:49,736: INFO/MainProcess] Received task: app.math[8f6caa15-0ce3-4125-a17e-de328168bfb1]
[2017-11-02 19:01:49,848: INFO/MainProcess] Task app.math[8f6caa15-0ce3-4125-a17e-de328168bfb1] succeeded in 120.11035105399787s: None
[2017-11-02 19:06:41,249: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-11-02 19:06:41,619: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-02 19:06:41,641: INFO/MainProcess] mingle: searching for neighbors
[2017-11-02 19:06:42,655: INFO/MainProcess] mingle: all alone
[2017-11-02 19:06:42,674: WARNING/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-02 19:10:42,248: INFO/MainProcess] Received task: app.script_runner[b4808d22-ce2a-4fe4-988a-b463be312b59]
[2017-11-02 19:10:42,261: INFO/Worker-1] app.script_runner[b4808d22-ce2a-4fe4-988a-b463be312b59]: ###  Matthew in script_runner celery task  ###
[2017-11-02 19:13:48,133: INFO/MainProcess] Received task: app.script_runner[e8e42071-a533-415e-89ed-7294b524602e]
[2017-11-02 19:13:48,145: INFO/Worker-3] app.script_runner[e8e42071-a533-415e-89ed-7294b524602e]: ###  Matthew in script_runner celery task  ###
